version: "2"
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gofmt:
      simplify: false
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"
        - pattern: "a[b:len(a)]"
          replacement: "a[b:]"
    gofumpt:
      module-path: github.com/naivary/nuage
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/naivary/nuage
    golines:
      max-len: 80
      tab-len: 2
      shorten-comments: true