package nuage

import "fmt"

// An RFC 9457 problem object
type HTTPError struct {
	// A URI reference that identifies the problem type.
	Type string
	// A short, human-readable summary of the problem type.
	Title string
	// The HTTP status code generated by the origin server for
	// this occurrence of the problem.
	Status int
	// A human-readable explanation specific to this occurrence
	// of the problem.
	Detail string
	// A URI reference that identifies the  specific occurrence of
	// the problem. It may or may not yield further information if
	// dereferenced.
	Instance string
}

func NewHTTPError(status int, format string, args ...any) *HTTPError {
	return &HTTPError{
		Status: status,
		Title:  fmt.Sprintf(format, args...),
	}
}

func (h *HTTPError) Error() string {
	return fmt.Sprintf("%d:%s", h.Status, h.Title)
}
