// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package nuage

import (
	"errors"
	"fmt"
)

const (
	SchemaTypeRequest  SchemaType = "request"
	SchemaTypeResponse SchemaType = "response"
)

var ErrInvalidSchemaType = errors.New("not a valid SchemaType")

// String implements the Stringer interface.
func (x SchemaType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SchemaType) IsValid() bool {
	_, err := ParseSchemaType(string(x))
	return err == nil
}

var _SchemaTypeValue = map[string]SchemaType{
	"request":  SchemaTypeRequest,
	"response": SchemaTypeResponse,
}

// ParseSchemaType attempts to convert a string to a SchemaType.
func ParseSchemaType(name string) (SchemaType, error) {
	if x, ok := _SchemaTypeValue[name]; ok {
		return x, nil
	}
	return SchemaType(""), fmt.Errorf("%s is %w", name, ErrInvalidSchemaType)
}

// MarshalText implements the text marshaller method.
func (x SchemaType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *SchemaType) UnmarshalText(text []byte) error {
	tmp, err := ParseSchemaType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *SchemaType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
